[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["Алексей <kochetkoov.ao@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
argparse = "^1.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
